# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# R8
android.enableR8.fullMode=false
android.enableR8=true

# Build cache
org.gradle.caching=true
org.gradle.parallel=true

# NDK
android.ndkVersion=25.2.9519653

# Disable warning for non-transitive R classes
android.nonTransitiveRClass=false
